### PR TITLE
Adding CDN for twig file.

### PR DESCRIPTION
**Pull request by mackstar**

### CODE REVIEW

**Comment by mackstar** [comment]
Shall I update it with the newer 

//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css
//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js

as suggested in your comment? Or do you want to rethink how we can keep these dependencies up to date across a BEAR installation. In this case I needed to change them or else the application was broken. Along with some other files.

**Comment by koriym** [comment]
Hi Rechad san, I'm aware of more importance to support Twig.

I think we need layout file as Smarty's. Also we need proper file cache setup at initialization. Anyway it's all about default setup. It should not affect anything in current setup in your application.

**Comment by koriym** [comment]
twigをこれ https://github.com/koriym/BEAR.Package/commit/c539f1891002fa930e6492cf684cde71a16b1b24 にしてSmarty同様にレイアウトファイルを使用をデフォルトにしようと思うのですがどうでしょうか。

**Comment by mackstar** [comment]
Yes I was going to do that, but I saw you already started it. In my BEAR applications I will be using Twig.

**Comment by koriym** [comment]
It would be nice you create layout-enable twig skeleton and push it.

**Comment by mackstar** [comment]
Okay I will do that, the PR will be in by Friday... Hopefully sooner ;-)

**Comment by koriym** [comment]
nice. maybe we should twig as default at that timing ?

**Comment by mackstar** [comment]
I know in US/Europe that Twig is favourable, in Japan people still like Smarty. It is choice. I will leave it up to you! ;-)

**Comment by koriym** [comment]
Let's follow the international standard. Anyway it's only default setting. BEAR.Sunday want to be a neutral for any template engine as other libs.

**Comment by koriym** [comment]
Also I will try to implement @ViewModel layer soon. This layer can be attached as `View Aspect` when it can solve view problem nicely.

**Comment by koriym** [comment]
I made the repo for installers on BEARSunday account. https://github.com/BEARSunday/installers

**Comment by mackstar** [comment]
The installer was just trying to get my head round it, I have since removed it. It would be nice to have a installer rule for apps.

**Comment by koriym** [comment]
Richard san, Are you going to prepare more twig stuff ? (like plugin) or shall I merge now ?

**Comment by kenjis** [comment]
This PR seems to be broken (Spout source is mixed?). Why don't you close?

I send PR for Twig layout-enable template: #20

**Comment by koriym** [comment]
yep. Thanks.

**Pull request closed without merging**
